[project]
name = "born-portal"
version = "0.1.0"
description = "Born portal"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles",
    "blacksheep",
    "httpx~=0.28",
    "jinja2",
    "litellm",
    "markdownify",
    "sqlmodel>=0.0.42",
    "uvicorn[standard]",
]

[build-system]
requires = ["uv_build<=0.12"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright",
    "pytest",
]

[tool.pyright]
pythonPath = ".venv/bin/python"

[project.scripts]
app = "born_portal.main:main"
event = "born_portal.event:main"
